// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO-jgaJRxXNTQeriHJkQCM6tf5tA81xMU',
    appId: '1:235028248924:web:7bd1de766e545d684d2999',
    messagingSenderId: '235028248924',
    projectId: 'my-trips-go',
    authDomain: 'my-trips-go.firebaseapp.com',
    storageBucket: 'my-trips-go.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArDAEEZtTXZrCJR9CSrfk4YkKSmovAxd8',
    appId: '1:235028248924:android:19c70faef73d56d24d2999',
    messagingSenderId: '235028248924',
    projectId: 'my-trips-go',
    storageBucket: 'my-trips-go.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD44RzHh3iDUQkU77RhZcghKgp_YqnjKw8',
    appId: '1:235028248924:ios:40daf71c619e89454d2999',
    messagingSenderId: '235028248924',
    projectId: 'my-trips-go',
    storageBucket: 'my-trips-go.firebasestorage.app',
    iosBundleId: 'com.mytripss.myTrips',
  );
}
